---
vagrant_hashicorp_gpg:
  key_path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  key_url: https://apt.releases.hashicorp.com/gpg

vagrant_hashicorp_deb822:
  uris: https://apt.releases.hashicorp.com
  suites: "{{ ansible_facts['distribution_release'] }}"
  components: ["main"]

vagrant_packages:
  - vagrant

vagrant_libvirt_dependencies:
  - libvirt-dev
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - bridge-utils
  - virt-manager
  - nfs-common
  - nfs-kernel-server
  - build-essential
  - zlib1g-dev
  - ruby-dev
  - libxml2-dev
  - libxslt-dev
  - libguestfs-tools
