---
# Kubernetes version (major.minor only, e.g., 1.28, 1.29, 1.30)
kubectl_version: "1.31"

kubectl_kubernetes_gpg:
  path: /usr/share/keyrings/kubernetes-apt-keyring.gpg
  tmp_path: "/tmp/kubernetes-apt-keyring.gpg"
  url: "https://pkgs.k8s.io/core:/stable:/v{{ kubectl_version }}/deb/Release.key"
  repo: "deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubectl_version }}/deb/ /"
