---
docker_gpg:
  path: /usr/share/keyrings/docker-archive-keyring.gpg
  url: https://download.docker.com/linux/ubuntu/gpg

docker_deb822:
  uris: https://download.docker.com/linux/ubuntu
  suites: "{{ ansible_facts['lsb']['codename'] }}"
  components: ["stable"]
  architectures: ["amd64"]
