---
galaxy_info:
  author: xgueret
  description: Install kubectl Kubernetes CLI tool
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie

dependencies: []
