---
galaxy_info:
  author: xgueret
  description: Install DevOps tools (AWS CLI v2, etc.) with auto-update
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []
